name: C++ CI

on:
  push:
    branches: [ "main"] #, "feature/**"]  # Or "master" or your main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu, you can also use windows-latest or macos-latest

    steps:
    - uses: actions/checkout@v3  # Checkout the code
    
    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake libgsl-dev # Install gtest and cmake

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug  # Configure the build

    - name: Build
      run: cmake --build build  # Build the project

    - name: Run Tests
      run: cd build && ctest --output-on-failure

    - name: Show detailed test output
      if: failure()
      run: cat build/Testing/Temporary/LastTest.log || echo "No LastTest.log found"
